name:                heb
version:             0.1.0.0
github:              "githubuser/heb"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/heb#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- persistent
- persistent-postgresql
- persistent-template
- esqueleto
- monad-logger
- mtl
- aeson
- time
- uuid
- random
- http-conduit
- amazonka-rekognition
- text
- bytestring
- lens
- hoauth2
- uri-bytestring
- http-client

library:
  source-dirs: src

executables:
  heb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - heb
    - text
    - filepath
    - containers
    - scotty

tests:
  heb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - heb
